### ISSUE TITLE
Add requests and yaml as dependencies

### ISSUE THREAD

**Issue by ddurdle** [mk-fg/python-onedrive#44]
Installed this on a few servers the other day.  The setup.py reports all dependencies met, but after you try to run, you realize there are dependencies on yaml and requests.  These should be flagged on the setup/install.

**Comment by mk-fg** [comment]
Well, they kinda "flagged" in setup.py:

    extras_require=dict(
      standalone=['requests'],
      cli=['PyYAML', 'requests'],
      conf=['PyYAML', 'requests']),

Trick is to install the thing via e.g. `pip install 'python-onedrive[cli]'`.

It's mentioned somewhere in the [grand README's appendix on installation](https://github.com/mk-fg/python-onedrive#installation), but I'm sure no one reads that anyway.

Idea behind this sorcery is to not require yaml for peoples who don't care about cli script (only that one uses yaml and does config stuff), as it's a python module to use from python after all.
And requests is actually not required either, as e.g. txonedrive module demonstrates (which is the only one I used onedrive through).

But guess there might be a better way to integrate this one with tx, plus yaml and that cli flag can probably be more obvious in the README.
It's a bit of an unfortunate coincidence that yaml is here at all, as I initially only added the tool to probe the api for dev purposes and yaml was simple for me, but it's not really needed there, and probably only complicates things for people.

Will do something about that... sometime.

**Comment by mk-fg** [comment]
Apparently README lacked even the basic explaination of these "extras" flags, so at least fixed that.

Probably not good enough for most real-world installs (one shouldn't expect people to read), but I'd really rather not add extra python module deps as required if they aren't such in all use-cases, erring on the "inconvenient" side of the "convenient - correct" choice here.
