### ISSUE TITLE
Putting file: No JSON object could be decoded

### ISSUE THREAD

**Issue by ddurdle** [mk-fg/python-onedrive#45]
Suddenly getting this error today.  Worked yesterday.  Today, on 3 different installs on 3 different systems:

When trying to put a 1MB file.
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==15.01.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/cli_tool.py", line 341, in main
    xres = api.put( optz.file, resolve_path(dst),
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/cli_tool.py", line 251, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or api.resolve_path(s))\
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/api_v5.py", line 562, in resolve_path
    root_id = dict(it.imap(op.itemgetter('name', 'id'), self.listdir(root_id)))[name]
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/api_v5.py", line 578, in listdir
    .listdir(folder_id=folder_id, limit=limit, offset=offset)['data']
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/api_v5.py", line 342, in listdir
    return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/api_v5.py", line 317, in __call__
    try: return self.request(api_url(), **kwz)
  File "/usr/local/lib/python2.7/dist-packages/python_onedrive-15.01.0-py2.7.egg/onedrive/api_v5.py", line 152, in request
    else: res = json.loads(res.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
cat: /sys/devices/platform/smapi/BAT0/power_now: No such file or directory

**Comment by vinodc** [comment]
I encountered this today too. Microsoft has been returning invalid gzip/deflate encoding. The requests module sets the header 'Accept-Encoding' to 'gzip,deflate' by default. I've modified my code to always send the headers "Accept-Encoding": "", in OneDriveHTTPClient's request(), which appears to resolve the problem:

Hotfix till this is resolved in the repo:
```python
class OneDriveAPI(api_v5.OneDriveAPI):
    def request(self, *args, **kwargs):
        kwargs.setdefault('headers', dict())['Accept-Encoding'] = ''
        return super(SkyDriveAPI, self).request(*args, **kwargs)
```

Would be great if we could introduce that header here, or figure out how to decode the encoded response.

**Comment by ddurdle** [comment]
Thanks vinodc!

Where are you putting this in the code?

**Comment by vinodc** [comment]
This was in my own code, where I overrode the request() method after inheriting from api_v5.OneDriveAPI.

**Comment by mk-fg** [comment]
All OneDrive calls seem to also fail for me in the same fashion at the moment, and @vinodc is right about the solution (or maybe rather a workaround until OneDrive devs address the issue), thanks for mentioning it here.

I've added maybe an easier option of setting "request_base_headers" dict in as subclass or instance (or maybe even monkey-patching on the actual class, though this practice is frowned upon), which will be used as a default headers for all requests.

In case of cli tool, this value can be tweaked by adding e.g.:

    request:
      base_headers:
        Accept-Encoding: ''

To the usual `~/.lcrc` file.

Not sure if this header should be set by default - probably not if it's a transient issue and will be resolved in a few hours, but if it's here to stay - definitely should be.
Will check back on it later and see, I guess.

Again, thank you guys for raising and pretty much resolving it here ;)

**Comment by mk-fg** [comment]
Oh, and yeah, as also mentioned by @vinodc, if this thing doesn't go away immediately, response should probably also be inspected to see what exactly went "wrong" there, maybe it's a gzip quirk or something.

**Comment by Orbyne** [comment]
I just found and read this thread and was about to implement the workaround but typically just as I didn that it seems to be resolved. Thanks for the workaround, good to know.

**Comment by mk-fg** [comment]
Resolved on OneDrive side for me too, it seems - guess they spotted the issue and fixed it, most awesome outcome possible \o/

But if it still happens occasionaly for anyone, do feel free to reopen, might be worth adding detection for such invalid encoding or something.
