### ISSUE TITLE
Avoid Dependency on the module

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [mk-fg/python-onedrive#46]
Hello
My apologies for this question and my little knowledge of english and more little about Python.
I have done all the steps in the installation and the permissions on the site of Microsoft; the file \.lcrc is correct according to the specifications.

I have reviewed all open incidents without finding any applicable.
I’m trying to access Onedrive to recover a list of files, using the following command 
          Onedrive-cli-script.py –c “B::\OD.lcrc” ls
dnd I obtain the following error
          Import requests # import here to avoid dependence on the module
following to the sentence
         File “C:\Python27\lib\site-packages\onedrive\api_v5.py”, line 98, in request

I enclose a image of the window.

Please, could anybody give any thing to do to solve it. I am completely stopped.
Thanks a lot in advance

![onedrive error](https://cloud.githubusercontent.com/assets/10756155/5956355/7168f112-a7ad-11e4-820d-ac497e4c0c86.jpg)

**Comment by mk-fg** [comment]
Hi,

This error tells you that python cannot find required (in this case) ["requests" module](http://docs.python-requests.org/), which is mentioned in the [requrements](https://github.com/mk-fg/python-onedrive/#requirements) and [installation](https://github.com/mk-fg/python-onedrive/#installation) sections of the README file.

Do you have it installed?
If not, you probably just need to do that.

I think it should've been installed if you followed instructions in the aforementioned "Installation" section of the README, but otherwise you can just easily install it after the fact, such ordering doesn't matter here at all.
There are detailed instructions on ways to install that module [in its documentation](http://docs.python-requests.org/en/latest/user/install/).

**Comment by ALEERQUESON2DIAS** [comment]
Hi,

Thank you very much for your reply

It is likely that, due to my lack of knowledge of Python, there is a problem in the installation, since I did it by using the following command in one of the many websites consulted

pip install https://pypi.python.org/packages/source/p/python-onedrive/python-onedrive-15.01.8.tar.gz

I will proceed with a clean reinstall following the indications that I have provided in your response.

Thank you very much

**Comment by mk-fg** [comment]
You're very welcome, and if you have "pip" command, you shouldn't need to go through any hassle re-installing stuff, just run `pip install requests` and it should all work from then on.

**Comment by ALEERQUESON2DIAS** [comment]
Thanks a lot, yes, ,I have pip and I will a complete new reinstallation using it, as recomended.

Thanks a lot..

**Comment by mk-fg** [comment]
It's actually called "requests" (extra "s" at the end, lowercase), and yeah, guess there won't be any harm in doing that.
Might surprise people used to python-default error messages, but don't think it should be a problem.

Thanks for the idea!

**Comment by mk-fg** [comment]
This particular error should dump something like this now (as of 15.01.10 and 7f47c2b):

    Traceback (most recent call last):
      File "./onedrive-cli", line 381, in <module>
        if __name__ == '__main__': main()
      File "./onedrive-cli", line 306, in main
        api.listdir(resolve_path(optz.folder), offset=offset, limit=limit),
      File "./onedrive/api_v5.py", line 608, in listdir
        .listdir(folder_id=folder_id, limit=limit, offset=offset)['data']
      File "./onedrive/api_v5.py", line 358, in listdir
        return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
      File "./onedrive/api_v5.py", line 333, in __call__
        try: return self.request(api_url(), **kwz)
      File "./onedrive/api_v5.py", line 108, in request
        try: import requestsx # import here to avoid dependency on the module
    ImportError: Unable to find/import "requests" module. Please make sure that it is installed, e.g. by running "pip install requests" command.
    For more info, visit: http://docs.python-requests.org/en/latest/user/install/
