### ISSUE TITLE
onedrive-d re-upload files every boot

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mk-fg/python-onedrive#49]
Every time i boot, i have onedrive-d at startup, my upload band get saturated and the notification applet get spammed by messages (see attached image).

The folder syncronized contains a symlink to a folder in a ntfs partition.

**Comment by mk-fg** [comment]
Umm... maybe you meant to open this issue in xybu92/onedrive-d?
I don't really have any control over that repository.

Also, there doesn't seem to be any attached image, not sure if it's even possible to "attach" image to a github issue, maybe only link these (from e.g. imgur.com or something).

**Comment by Alessandro-Barbieri** [comment]
Sorry might! I forgot to attach image.
![area notifica spam tagliata](https://cloud.githubusercontent.com/assets/10689739/6193642/a8667fc4-
b3bd-11e4-9120-7759c06d1e9d.png)

github supports cross-project issues?

**Comment by mk-fg** [comment]
> github supports cross-project issues?

Don't think so, best way I know of is to just re-open in the destination project and copy-paste the text.
