### ISSUE TITLE
Registering in DevCenter, incorrect link?

### ISSUE THREAD

**Issue by noureddin** [mk-fg/python-onedrive#51]
The readme referes to "https://dev.live.com/" in this paragraph: "OneDrive API requires to register an application in DevCenter, providing you with client_id and client_secret strings, used for authentication."
which seems to be changed after the readme has been updated.
Anyway, I've reached this link "https://account.live.com/developers/applications/create" which seems to be the intended one.

**Comment by mk-fg** [comment]
Indeed, it's been years since I've pasted that url, and the one you propose seem to work way better these days.
Updated now to use that URL everywhere dev.live.com was used before, thanks!
