### ISSUE TITLE
New OneDrive API support

### ISSUE THREAD

**Issue by zmwangx** [mk-fg/python-onedrive#52]
Today (Feb 24, 2015), Microsoft announced [the new OneDrive API](http://onedrive.github.io/index.htm). It seems that there are a lot of changes. One change that I'm particularly interested in is that [large file upload](http://onedrive.github.io/items/upload_large_files.htm) is now official; however, it uses standard HTTP `POST` rather than the BITS protocol.

**Comment by mk-fg** [comment]
Wow, that is quite amazing, both from "moved to github" (not necessarily good) and "great stuff" perspectives.
Thanks for mentioning it here.

I can't make any promises about whether or when it will be implemented, as it looks like a bit of work, and I don't really use OneDrive myself at the moment.

**Comment by zmwangx** [comment]
No problem, just want to note it here. I might also contribute some bits and pieces if legacy code breaks down and if I can figure out some time for rewriting (not very likely in the coming months).

By the way, I'd like to say thank you for this package. It's been very helpful for me.

**Comment by ddurdle** [comment]
They actually use PUT to push data > 100MB or POST if you can get a file < 100MB to upload without timing out.  After this past weekend of having all my BITS transfers fail (meaning would result in error 500 and repeatedly so on all reattempts) across 3 machines connected to three different networks (so it was a Microsoft issue, not a network connection issue), I decided to take a crack at trying the OneDrive API1.

Got a file uploader together and I'm testing.  The BITS issue from the weekend was promptly resolved on Monday morning, so I've fallen back to using python-onedrive, but I'm testing the implementation against  OneDrive API1 on the side.  Too early to judge, but I expected it to be faster (in addition to more reliable).  On a system that I get a reliable and steady 10MB/s up to Google Drive, I'm getting about 1MB/s up to OneDrive API1 for large file transfers.  I'll have to try different chunk sizes, but it looks like there is no "speed" gain.  Hopefully there is some better reliability.

**Comment by mk-fg** [comment]
PUT vs POST actually makes a lot of sense, as you need special encoding for data in POST body and in PUT you can either only pass size or don't even do that - use "content-encoding: chunked" and stream whatever gigs of data.

Pity about BITS, but I guess it might have been just a (failed) experiment at extending old API.

**Comment by ddurdle** [comment]
I really can't comment on the BITS protocol since I never implemented anything to use it :)  I just relied on your code.  Issues I know I encountered were issues with token expiring (so auto refresh it before uploading large files) and random error 500/503 while uploading, which force me to re-upload the entire file (granted I'm running your onedrive-cli in a script and if it dies with an error, it reruns the last call, so re-upload).

I tested an implementation I put together (simple script) using the new API.  I noticed the token can expire still (received the error last night after uploading a chunk of a file at some point into the transfer).  But in my script, I capture the error and "refresh" the token and then carry on and resend the failed chunk (which succeeds), then I carry on with the remainder of the file.  The file does finish, and I do see it show up in OneDrive.  I have to assume this is like Google Drive, and will now allow the file to show up in OneDrive if it is not complete.  I'm just a bit fuzzy how it knows I'm done with the file.  In Google Drive, I need to tell Google the size of the file, and it knows if it doesn't receive the agreed upon number of chunks, it will consider the file incomplete, and never shows up in the interface.  In this new OneDrive API1, you don't pass it a file size, just start passing chunks.  I'm taking extra effort to cross check file sizes that show up in the interface.  I should probably do CRC32 checks to validate the files didn't become corrupt.

On the same discussion, I'm doing the same logic for any error (not just expired token).  Any error on client end "disconnect by peer" or 50x error by server, it will back-off and retry the chunk again up to 5 times before considering it a lost-cause and abort the transfer.  I think again OneDrive assumes you will send an abort to invalidate the file.

**Comment by ddurdle** [comment]
I'm also excited by the remote URL feature.  I've thrown a couple test cases at it so far and they've all passed.  An alternative way of getting stuff into your OneDrive.

**Comment by ddurdle** [comment]
Sorry, here's the link: http://onedrive.github.io/items/upload_url.htm

**Comment by ddurdle** [comment]
I know that there are third-parties that provide this service to Google Drive/etc, but they are exactly that -- a third party that downloads and then uploaded the data to your account.  Microsoft closes that loop by feeding it directly into your account

**Comment by zmwangx** [comment]
@ddurdle 
> I have to assume this is like Google Drive, and will now allow the file to show up in OneDrive if it is not complete.

Seriously? That's not cool. Could you elaborate on what you saw?

> I'm also excited by the remote URL feature.

Yeah, that's great. But if files show up even when transfer fails in the middle, as you reported, then it's extremely hard to guarantee integrity (you can compare the number of bytes to the number of bytes reported in the header, but other than that, nothing).

**Comment by zmwangx** [comment]
Or maybe "now allow the file to show up" is a typo and you really mean "not allow the file to show up"?

**Comment by ddurdle** [comment]
I meant.... I was hoping that if you are uploading a file or have not completed an upload successfully, that it would not show up (so remain invisible), like the way it is done on Google Drive (shows up only seconds after it is complete).  I had another look at the API call, and although you don't pass a filesize explicitly, it is part of the range (the example on the API shows a range of "bytes 0 - 23 / 24").  I did some further tests today and I can confirm that while a file is being uploaded, it does not show up until it is complete uploading.

Regarding the remote URL, there is a status URL you can call to see the %.  I confirmed the file doesn't show up in the drive until it is finished.  I guess you would either need to poll the status or do a drive listing to validate the file completed successfully.  Last thing you want to do is a batch load of 1000 files and find out only 998 show up :)

**Comment by zmwangx** [comment]
> I did some further tests today and I can confirm that while a file is being uploaded, it does not show up until it is complete uploading.

Okay that's good, and I believe that's how the old API handled uploads all along.

> Last thing you want to do is a batch load of 1000 files and find out only 998 show up :)

You can still (recursively) list and compare with the expected list or tree. Nerve-racking and painful, I agree.

**Comment by mk-fg** [comment]
> Sorry, here's the link: http://onedrive.github.io/items/upload_url.htm

Interesting feature, indeed.
Hopefully people won't find too many ways to abuse it "for lulz", so that it might become more mainstream.

**Comment by mk-fg** [comment]
> Last thing you want to do is a batch load of 1000 files and find out only 998 show up :)

One ridiculous hack might be in using something like [Reed–Solomon error correction](https://en.wikipedia.org/wiki/Reed-solomon_codes), if percentage of "lost chunks" is predictable and fairly low.

> On the same discussion, I'm doing the same logic for any error (not just expired token). Any error on client end "disconnect by peer" or 50x error by server, ...

New API randomly returns 5XX-series errors too?
I mean, using same logic is one thing, but I'd be kinda surprised if it actually happens, sounds like an API bug that shouldn't have been missed.

**Comment by mk-fg** [comment]
> One ridiculous hack ...

Um, nope, just realized that you're probably talking about uploading whole files to the cloud as-is, won't work like that, of course.

**Comment by ddurdle** [comment]
I meant to log error occurrences to a log but that didn't work out as the log file is empty.  What I saw on the console before it scrolled off forever, was that there were a number of failures due to the client side due to "client disconnected from peer" type errors.  I haven't "seen" any error 500s yet, but that doesn't mean non occurred in my recent batch job run.  What I do know is that all my files uploaded and are showing without issue on my OneDrive.

so far, so good.

**Comment by ddurdle** [comment]
I ran a test last night against a youtube url (did smaller tests, and they worked, prior).

**Comment by ddurdle** [comment]
The video was 700MB.  It took 30 mins to get to 50% downloaded (querying the status URL).  I walked away, assuming it would finish at 30 mins later.  Came back in 30 mins and the status URL displayed error 404 (which is does if the file completed or did not complete).  File never made it into my OneDrive.  There must have been a download error in the last 50%.  There is no way of validating this it would appear.  The status URL should remain functional afterwards to indicate success/failure.

For comparison, on a VPS, I can download (and have) the 700MB in 4 seconds, upload it to Google Drive in 3 mins, and upload it to onedrive-cli in 6 mins.  Much more viable it seems then remote upload.

**Comment by ddurdle** [comment]
I've seen these so far:

Content-Range: bytes 260046848-262143999/424600062
Content-Type: application/octet-stream
Keep-Alive: 300
500 Status read failed: Connection reset by peer

Technically error 500.  But they recover if I try the chunk.

**Comment by zmwangx** [comment]
Just for the record, I wrote an uploader (uploader only at the moment — might expand if it turns out that I need other features) using the new API: https://github.com/zmwangx/pyonedrive. The code is utterly crap, but from my limited testing it's more reliable than `python-onedrive` in uploading large files (think of vanilla CLI) — especially when uploading many files at once. Plus it has builtin support for concurrency, and a few other bells and whistles.

**Comment by ddurdle** [comment]
If anyone has any desire to cope with a complicated and still-developing sync tool, I extended my PERL Google Drive scripts to include OneDrive https://github.com/ddurdle/PERL-CloudSync

I use it to download or upload folders.  Also a unique feature, and intended purpose of the product, is to allow for sync drives or folders between Google Drives and OneDrives.  For example, I use it to sync one Google Drive with 2 others Google Drives + OneDrive.  To determine what to sync, between Google Drives, it uses MD5 checksums, between OneDrives, it uses SHA1 checksums, and when determine what to sync between Google Drive <-> OneDrive, it uses filename+filesize.  I use dbm files to keep track of folders and checksums, so it is able to sync drives with thousands of files without consuming a lot of memory (typical 22mb footprint).  So, it has been proving well for me on VPS and micro computers.

I'm still implementing a client/server model that would allow an instance spawn multiple sub-instances for transfers (if you have 3 internet connections, you want to split the workload out across connections).  Right now, I'm just running 3 instances, each bound to a different IP, and having each sync different payload folders.

**Comment by mk-fg** [comment]
There's now proper and official [onedrive-sdk-python](https://github.com/OneDrive/onedrive-sdk-python) module available, should probably be used instead for any new projects.
