### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by furieuxjk** [mk-fg/python-onedrive#61]
Hello.

First of all - thanks for this great project!

Is it possible to upload multiple files in directory recursively? Or maybe even whole folder upload?

**Comment by mk-fg** [comment]
Hi, thanks.

Not with a cli tool that comes with this module, I'm afraid, it's pretty basic and more of an "example code".
At least, not without some extra scripting on top of it (e.g. a bash script to run "mkdir" then individual "put" operations for each file).

I think there are projects built on top of this module, like xybu/onedrive-d, that should be able to do the trick, and even continuously sync changes in such directory afterwards.

**Comment by furieuxjk** [comment]
Ok, thanks for the answer.
