### ISSUE TITLE
Put() cannot pass string of bytes

### ISSUE THREAD

**Issue by W4RH4WK** [mk-fg/python-onedrive#62]
according to the docstring i should be able to pass a tupe to `put()` in the form of `(file_name, string_of_bytes)` but when i do, i get an `AttributeError` because `seek` does not work on a string.

see https://github.com/mk-fg/python-onedrive/blob/18518c188248877213e922e75a2e4665bb49cc15/onedrive/api_v5.py#L436

**Comment by mk-fg** [comment]
Thanks.
Yeah, definitely looks like a bug.

**Comment by mk-fg** [comment]
Pushed fix in 18b4286 (and on pypi too), can you try if it works now?

**Comment by W4RH4WK** [comment]
yep, seems to work just fine, thanks. note that i tested it only with cpython not pypi.

**Comment by mk-fg** [comment]
Heheh, you're probably confusing "PyPy" - http://pypy.org/ - fast python interpreter, cPython alternative, with "PyPI" (as I meant it) - http://pypi.python.org/ - Python Package Index.

I just meant that "new version of package is on pypi, so you can update it via `pip install --upgrade python-onedrive` (or something like that) to test new changes" ;)

Thanks for catching the bug and testing!

**Comment by W4RH4WK** [comment]
yes i mixed that up, downloaded it straight from pypi
